package wizard.projectwizard.kmparch

import wizard.projectwizard.data.KMPConfigModel
import com.intellij.ide.fileTemplates.FileTemplateManager
import com.intellij.ide.starters.local.GeneratorAsset
import com.intellij.ide.starters.local.GeneratorTemplateFile
import com.intellij.openapi.vfs.VirtualFile

class CommonFileGenerator(
    params: KMPConfigModel,
    private val dataModel: MutableMap<String, Any>,
    private val virtualFile: VirtualFile,
) : FileGenerator(params) {
    override fun generate(ftManager: FileTemplateManager, packageName: String): List<GeneratorAsset> {
        val list = mutableListOf<GeneratorAsset>()
        return list.apply {
            addAll(
                listOf(
                    GeneratorTemplateFile(
                        "build.gradle.kts",
                        ftManager.getCodeTemplate(Template.GRADLE_KTS)
                    ),
                    GeneratorTemplateFile(
                        "settings.gradle.kts",
                        ftManager.getCodeTemplate(Template.SETTINGS_GRADLE)
                    ),
                    GeneratorTemplateFile(
                        "gradle.properties",
                        ftManager.getCodeTemplate(Template.GRADLE_PROPERTIES)
                    ),
                    GeneratorTemplateFile(
                        "gradle/wrapper/gradle-wrapper.properties",
                        ftManager.getCodeTemplate(Template.GRADLE_WRAPPER_PROPERTIES)
                    ),
                    GeneratorTemplateFile(
                        "gradle/libs.versions.toml",
                        ftManager.getCodeTemplate(Template.TOML)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/App.kt",
                        ftManager.getCodeTemplate(Template.COMMON_APP)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/composeResources/drawable/compose-multiplatform.xml",
                        ftManager.getCodeTemplate(Template.COMMON_COMPOSE_RESOURCES_MULTIPLATFORM_XML)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/build.gradle.kts",
                        ftManager.getCodeTemplate(Template.COMPOSE_GRADLE_KTS)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonTest/kotlin/$packageName/ComposeAppCommonTest.kt",
                        ftManager.getCodeTemplate(Template.COMPOSE_APP_COMMON_TEST)
                    ),
                    // Material Demos
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/ComponentDemos.kt",
                        ftManager.getCodeTemplate(Template.COMPONENT_DEMOS)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/Greeting.kt",
                        ftManager.getCodeTemplate(Template.GREETING)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/Platform.kt",
                        ftManager.getCodeTemplate(Template.PLATFORM)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/navigation/Navigation.kt",
                        ftManager.getCodeTemplate(Template.NAVIGATION)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/benchmark/Compose1500Text.kt",
                        ftManager.getCodeTemplate(Template.COMPOSE_1500_TEXT)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/benchmark/Compose1500view.kt",
                        ftManager.getCodeTemplate(Template.COMPOSE_1500_VIEW)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/foundation/BasicTextDemo.kt",
                        ftManager.getCodeTemplate(Template.BASIC_TEXT_DEMO)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/foundation/LazyColumnDemo.kt",
                        ftManager.getCodeTemplate(Template.LAZY_COLUMN_DEMO)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/ui/BoxDemo.kt",
                        ftManager.getCodeTemplate(Template.BOX_DEMO)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/AlertDialogSample.kt",
                        ftManager.getCodeTemplate(Template.ALERT_DIALOG_SAMPLE)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/AppBarSamples.kt",
                        ftManager.getCodeTemplate(Template.APP_BAR_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/BackdropScaffoldSamples.kt",
                        ftManager.getCodeTemplate(Template.BACKDROP_SCAFFOLD_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/BadgeSamples.kt",
                        ftManager.getCodeTemplate(Template.BADGE_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/BottomNavigationSamples.kt",
                        ftManager.getCodeTemplate(Template.BOTTOM_NAVIGATION_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/BottomSheetScaffoldSamples.kt",
                        ftManager.getCodeTemplate(Template.BOTTOM_SHEET_SCAFFOLD_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/ButtonSamples.kt",
                        ftManager.getCodeTemplate(Template.BUTTON_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/CardSamples.kt",
                        ftManager.getCodeTemplate(Template.CARD_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/ContentAlphaSamples.kt",
                        ftManager.getCodeTemplate(Template.CONTENT_ALPHA_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/DrawerSamples.kt",
                        ftManager.getCodeTemplate(Template.DRAWER_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/ElevationSamples.kt",
                        ftManager.getCodeTemplate(Template.ELEVATION_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/ExposedDropdownMenuSamples.kt",
                        ftManager.getCodeTemplate(Template.EXPOSED_DROPDOWN_MENU_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/FloatingActionButtonSamples.kt",
                        ftManager.getCodeTemplate(Template.FLOATING_ACTION_BUTTON_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/IconButtonSamples.kt",
                        ftManager.getCodeTemplate(Template.ICON_BUTTON_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/ListSamples.kt",
                        ftManager.getCodeTemplate(Template.LIST_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/MenuSamples.kt",
                        ftManager.getCodeTemplate(Template.MENU_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/ModalBottomSheetSamples.kt",
                        ftManager.getCodeTemplate(Template.MODAL_BOTTOM_SHEET_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/NavigationRailSample.kt",
                        ftManager.getCodeTemplate(Template.NAVIGATION_RAIL_SAMPLE)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/ProgressIndicatorSamples.kt",
                        ftManager.getCodeTemplate(Template.PROGRESS_INDICATOR_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/PullRefreshSamples.kt",
                        ftManager.getCodeTemplate(Template.PULL_REFRESH_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/SelectionControlsSamples.kt",
                        ftManager.getCodeTemplate(Template.SELECTION_CONTROLS_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/SliderSample.kt",
                        ftManager.getCodeTemplate(Template.SLIDER_SAMPLE)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/SurfaceSamples.kt",
                        ftManager.getCodeTemplate(Template.SURFACE_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/SwipeableSamples.kt",
                        ftManager.getCodeTemplate(Template.SWIPEABLE_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/SwipeToDismissSamples.kt",
                        ftManager.getCodeTemplate(Template.SWIPE_TO_DISMISS_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/TabSamples.kt",
                        ftManager.getCodeTemplate(Template.TAB_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/TextFieldSamples.kt",
                        ftManager.getCodeTemplate(Template.TEXT_FIELD_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/TextSamples.kt",
                        ftManager.getCodeTemplate(Template.TEXT_SAMPLES)
                    ),
                    GeneratorTemplateFile(
                        "composeApp/src/commonMain/kotlin/$packageName/demos/material/ThemeSamples.kt",
                        ftManager.getCodeTemplate(Template.THEME_SAMPLES)
                    ),
                )
            )
        }.toList()
    }
}