package wizard.projectwizard.cmparch

import wizard.projectwizard.data.CMPConfigModel
import com.intellij.ide.fileTemplates.FileTemplateManager
import com.intellij.ide.starters.local.GeneratorAsset
import com.intellij.ide.starters.local.GeneratorTemplateFile
import com.intellij.ide.starters.local.GeneratorResourceFile

class HarmonyFileGenerator(params: CMPConfigModel) : FileGenerator(params) {
    override fun generate(ftManager: FileTemplateManager, packageName: String): List<GeneratorAsset> {
        return listOf(
            GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/kotlin/$packageName/ArkUIView.kt",
                ftManager.getCodeTemplate(Template.ARKUI_VIEW)
            ),
             GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/kotlin/$packageName/InteropListNested.kt",
                ftManager.getCodeTemplate(Template.INTEROP_LIST_NESTED)
            ),
             GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/kotlin/$packageName/InteropListSimple.kt",
                ftManager.getCodeTemplate(Template.INTEROP_LIST_SIMPLE)
            ),
            GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/kotlin/$packageName/InteropRenderOrder.kt",
                ftManager.getCodeTemplate(Template.INTEROP_RENDER_ORDER)
            ),
             GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/kotlin/$packageName/InteropTextInput.kt",
                ftManager.getCodeTemplate(Template.INTEROP_TEXT_INPUT)
            ),
             GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/kotlin/$packageName/MainArkUIViewController.kt",
                ftManager.getCodeTemplate(Template.MAIN_ARK_UI)
            ),
             GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/kotlin/$packageName/Platform.ohos.kt",
                ftManager.getCodeTemplate(Template.PLATFORM_OHOS)
            ),
             GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/cinterop/include/raw_file.h",
                ftManager.getCodeTemplate(Template.RAW_FILE)
            ),
             GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/cinterop/include/raw_file_manager.h",
                ftManager.getCodeTemplate(Template.RAW_FILE_MANAGER)
            ),
              GeneratorTemplateFile(
                "composeApp/src/ohosArm64Main/cinterop/resource.def",
                ftManager.getCodeTemplate(Template.RESOURCE_DEF)
            ),

             GeneratorTemplateFile(
                "harmonyApp/.gitignore",
                ftManager.getCodeTemplate(Template.GIT_IGNORE)
            ),
             GeneratorTemplateFile(
                "harmonyApp/build-profile.json5",
                ftManager.getCodeTemplate(Template.BUILD_PROFILE_JSON5)
            ),
             GeneratorTemplateFile(
                "harmonyApp/code-linter.json5",
                ftManager.getCodeTemplate(Template.CODE_LINTER_JSON5)
            ),
            GeneratorTemplateFile(
                "harmonyApp/hvigorfile.ts",
                ftManager.getCodeTemplate(Template.HVIGORFILE)
            ),
            GeneratorTemplateFile(
                "harmonyApp/oh-package-lock.json5",
                ftManager.getCodeTemplate(Template.OH_PACKAGE_LOCK_JSON5)
            ),
              GeneratorTemplateFile(
                "harmonyApp/oh-package.json5",
                ftManager.getCodeTemplate(Template.OH_PACKAGE_JSON5)
            ),

            GeneratorTemplateFile(
                "harmonyApp/AppScope/app.json5",
                ftManager.getCodeTemplate(Template.APP_JSON5)
            ),
            GeneratorTemplateFile(
                "harmonyApp/AppScope/resources/base/element/string.json",
                ftManager.getCodeTemplate(Template.STRING_JSON)
            ),
             GeneratorTemplateFile(
                "harmonyApp/AppScope/resources/base/element/string.json",
                ftManager.getCodeTemplate(Template.STRING_JSON)
            ),
             GeneratorTemplateFile(
                "harmonyApp/AppScope/resources/base/media/layered_image.json",
                ftManager.getCodeTemplate(Template.LAYERED_IMAGE)
            ),
            GeneratorResourceFile(
                "harmonyApp/AppScope/resources/base/media/background.png",  
               this::class.java.classLoader.getResource("static/background.png")!! 
            ),
            GeneratorResourceFile(
                "harmonyApp/AppScope/resources/base/media/foreground.png", 
               this::class.java.classLoader.getResource("static/foreground.png")!! 
            ),
            GeneratorTemplateFile(
                "harmonyApp/entry/build-profile.json5",
                ftManager.getCodeTemplate(Template.ENTRY_BUILD)
            ),
            GeneratorTemplateFile(
                "harmonyApp/entry/.gitignore",
                ftManager.getCodeTemplate(Template.ENTRY_GIT_IGNORE)
            ),
            GeneratorTemplateFile(
                "harmonyApp/entry/hvigorfile.ts",
                ftManager.getCodeTemplate(Template.ENTRY_HVIGORFILE)
            ),
            GeneratorTemplateFile(
                "harmonyApp/entry/obfuscation-rule.txt",
                ftManager.getCodeTemplate(Template.ENTRY_OBFUSCATION)
            ),
            GeneratorTemplateFile(
                "harmonyApp/entry/oh-package-lock.json5",
                ftManager.getCodeTemplate(Template.ENTRY_OH_LOCK)
            ),
            GeneratorTemplateFile(
                "harmonyApp/entry/oh-package.json5",
                ftManager.getCodeTemplate(Template.ENTRY_OH)
            ),
            GeneratorResourceFile(
                "harmonyApp/entry/libs/compose.har", 
               this::class.java.classLoader.getResource("static/compose.har")!! 
            ),
            GeneratorResourceFile(
               "harmonyApp/entry/libs/skikobridge.har", 
               this::class.java.classLoader.getResource("static/skikobridge.har")!! 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/module.json5", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_MODULE) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/cpp/CMakeLists.txt", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_CPP_CAMKE) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/cpp/napi_init.cpp", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_CPP_NAPI) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/cpp/include/libkn_api.h", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_CPP_INCLUDE_LIB) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/cpp/types/libentry/Index.d.ts", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_CPP_TYPES_LIBENTRY_INDEX) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/cpp/types/libentry/oh-package.json5", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_CPP_TYPES_LIBENTRY_OH) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/ets/entryability/EntryAbility.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_ETS_ENTRYABILITY) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/ets/entrybackupability/EntryBackupAbility.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_ETS_ENTRYBACK) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/ets/pages/ComposeInterops.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_ETS_PAGES_COMPOSEINTEROPS) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/ets/pages/ComposeSample.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_ETS_PAGES_COMPOSESAMPLE) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/ets/pages/Index.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_ETS_PAGES_INDEX) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/resources/base/element/color.json", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_RESOURCES_BASE_ELEMENT_COLOR) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/resources/base/element/float.json", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_RESOURCES_BASE_ELEMENT_FLOAT) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/resources/base/element/string.json", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_RESOURCES_BASE_ELEMENT_STRING) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/resources/base/media/layered_image.json", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_RESOURCES_BASE_MEDIA_LAYERED) 
            ),
            GeneratorResourceFile(
               "harmonyApp/entry/src/main/resources/base/media/startIcon.png", 
               this::class.java.classLoader.getResource("static/startIcon.png")!! 
            ),
            GeneratorResourceFile(
               "harmonyApp/entry/src/main/resources/base/media/foreground.png", 
               this::class.java.classLoader.getResource("static/foreground.png")!! 
            ),
            GeneratorResourceFile(
               "harmonyApp/entry/src/main/resources/base/media/background.png", 
               this::class.java.classLoader.getResource("static/background.png")!! 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/resources/base/profile/backup_config.json", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_RESOURCES_BASE_PROFILE_BACKUP) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/resources/base/profile/main_pages.json", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_RESOURCES_BASE_PROFILE_MAIN) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/main/resources/dark/element/colors.json", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MAIN_RESOURCES_DARK_ELEMENT) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/mock/Libentry.mock.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MOCK_LIBENTRY) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/mock/mock-config.json5", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_MOCK_MOCK) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/ohosTest/module.json5", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_OHOSTEST_MODULE) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/ohosTest/ets/test/Ability.test.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_OHOSTEST_ETS_TEST_ABILITY) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/ohosTest/ets/test/List.test.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_OHOSTEST_ETS_TEST_LIST) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/test/List.test.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_TEST_LIST) 
            ),
            GeneratorTemplateFile(
               "harmonyApp/entry/src/test/LocalUnit.test.ets", 
               ftManager.getCodeTemplate(Template.ENTRY_SRC_TEST_LOCAL) 
            ),

            GeneratorTemplateFile(
               "harmonyApp/hvigor/hvigor-config.json5", 
               ftManager.getCodeTemplate(Template.HVIGOR_CONFIG) 
            ),

        )
    }
}